### ISSUE TITLE
Customizable Modifier (exposing modifier)

### ISSUE THREAD

**Issue by mooyoul** [Perlmint/i18next-korean-postposition-processor#3]
Hello @Perlmint , First of all, Thanks for your amazing work!
We're trying to use this package for processing postpositions in our notification localization texts.

Currently, we uses html based string templates. 
One of template looks like this:  `username님이 <b>#레드벨벳</b>을 좋아합니다.`
so, actual rendered text will be:
> username님이 **#레드벨벳**을 좋아합니다.

Anyway, current implementation treats enclosing character `>` as normal character.
So when template `{{ username }}님이 <b>#{{ community }}</b>[[를]] 좋아합니다` with parameter `{ username: 'mooyoul', community: '레드벨벳' }` will return `mooyoul님이 <b>#레드벨벳</b>를 좋아합니다`.

So i needed to strip enclosing tags from our input like this: https://github.com/balmbees/i18next-korean-postposition-processor/commit/df4f3ccc4ad7b2a80f03925209b4acb415b398b0

I thought this is quick & dirty solution to solve our problem. (that's why i didn't open PR also) Many use-cases in near future will require creating additional modifier, if someone uses markdown in their template, they should strip markdown from their template like we did.

So i propose customizable modifier - Users should be able to add their own modifier.

```typescript
import * as i18next from "i18next";
import KoreanPostProcessor from "i18next-korean-postposition-processor";

import * as stripTags from "striptags";
function htmlStripModifier(input: string) {
  return stripTags(input);
}

i18next
  .use(KoreanPostProcessor()) // default
  .use(KoreanPostProcessor({ // customizable
    modifiers: [
      htmlStripModifier,
      // add more modifier if needed
    ],
  }))
  .init();
```

**Comment by mooyoul** [comment]
v0.4.0 resolves this issue. Closing

**Comment by mooyoul** [comment]
v0.4.0 resolves this issue. Closing.

**Comment by Perlmint** [comment]
v0.4.0 is published
