### ISSUE TITLE
Conflicting peer dependency: i18next@12.1.0

### ISSUE THREAD

**Issue by almchung** [Perlmint/i18next-korean-postposition-processor#35]
Hi @Perlmint,

First of all, thank you for creating the Korean postposition plug-in for i18next.

I'm in the process of using the plug-in to build an internationalization module for p5.js, a JavaScript graphical library. I'm trying to resolve the `Conflicting peer dependency: i18next@12.1.0` error, which I get from using `i18next ^v19.0.2`, and was wondering if there is a dependency update planned for the near future. 

Thank you for your response in advance.

**Comment by Perlmint** [comment]
Thanks for reporting :).

I fixed a version of dependency and some errors about the newer i18next. And I just published a new version of this plugin.

Please try with [version 1.0.0](https://www.npmjs.com/package/i18next-korean-postposition-processor/v/1.0.0). It should work with i18next 19.

**Comment by almchung** [comment]
Awesome! It works great with v1.0.0, thank you!
